#!/bin/tcsh
# submit with qsub < [job.lsf]

#PBS -N run_p2p_forcings
#PBS -A P48500028
#PBS -q regular
#PBS -l select=1:ncpus=36:mpiprocs=36
#PBS -l walltime=02:30:00
#PBS -m abe
#PBS -M sgangra1@vols.utk.edu
# #PBS -o /glade/scratch/gangrade/temp/run_p2p_forcings.out
# #PBS -e /glade/scratch/gangrade/temp/run_p2p_forcings.err

setenv TmpDir /glade/scratch/gangrade/temp
module load python/2.7.16
ncar_pylib
mkdir -p $TmpDir

### Run the executable
setenv MPI_SHEPHERD true
# mpiexec_mpt launch_cf.sh /glade/work/gangrade/Summa_Preprocessing/02_Reproject/forcings/joblist.run_p2p.XXXRUNXXX.txt
mpiexec_mpt launch_cf.sh /glade/work/gangrade/Summa_Preprocessing/02_Reproject/forcings/joblist.run_p2p.4.txt